### ISSUE TITLE
Make a new Todo page

### ISSUE THREAD

**Issue by Neil-G** [Neil-G/todoExample#1]
- [x] make a a Todo page in /components/pages
- [x] export that page from the index
- [x] import the page in the routes file
- [x] make the page available at "/todos"

**Comment by Neil-G** [comment]
all done, reviewed, and merged
